pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                script { withSonarQubeEnv(credentialsId: 'SonarQube', installationName: 'MySonarQube') { // You can override the credential to be used
                        sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:4.8.0.2856:sonar'
                        }
                }
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        // stage('Deliver') {
        //     steps {
        //         sh './jenkins/scripts/deliver.sh'
        //     }
        // }
    }
}
